/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppWithdrawRouteImport } from './routes/_app/withdraw'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppSecurityRouteImport } from './routes/_app/security'
import { Route as AppReferralsRouteImport } from './routes/_app/referrals'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPlansRouteImport } from './routes/_app/plans'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppDepositRouteImport } from './routes/_app/deposit'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAdminEarningsRouteImport } from './routes/_app/admin-earnings'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppProfileSecurityRouteImport } from './routes/_app/profile/security'
import { Route as AppProfileSecurityLoginPasswordRouteImport } from './routes/_app/profile/security/login-password'
import { Route as AppProfileSecurityFundPasswordRouteImport } from './routes/_app/profile/security/fund-password'
import { Route as AppWithdrawCryptoUsdtBep20RouteImport } from './routes/_app/withdraw_.crypto.usdt.bep20'
import { Route as AppDepositCryptoUsdtBep20RouteImport } from './routes/_app/deposit_.crypto.usdt.bep20'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralsRoute = AppReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositRoute = AppDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEarningsRoute = AppAdminEarningsRouteImport.update({
  id: '/admin-earnings',
  path: '/admin-earnings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileSecurityRoute = AppProfileSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileSecurityLoginPasswordRoute =
  AppProfileSecurityLoginPasswordRouteImport.update({
    id: '/login-password',
    path: '/login-password',
    getParentRoute: () => AppProfileSecurityRoute,
  } as any)
const AppProfileSecurityFundPasswordRoute =
  AppProfileSecurityFundPasswordRouteImport.update({
    id: '/fund-password',
    path: '/fund-password',
    getParentRoute: () => AppProfileSecurityRoute,
  } as any)
const AppWithdrawCryptoUsdtBep20Route =
  AppWithdrawCryptoUsdtBep20RouteImport.update({
    id: '/withdraw_/crypto/usdt/bep20',
    path: '/withdraw/crypto/usdt/bep20',
    getParentRoute: () => AppRoute,
  } as any)
const AppDepositCryptoUsdtBep20Route =
  AppDepositCryptoUsdtBep20RouteImport.update({
    id: '/deposit_/crypto/usdt/bep20',
    path: '/deposit/crypto/usdt/bep20',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/support': typeof SupportRoute
  '/admin': typeof AppAdminRoute
  '/admin-earnings': typeof AppAdminEarningsRoute
  '/dashboard': typeof AppDashboardRoute
  '/deposit': typeof AppDepositRoute
  '/notifications': typeof AppNotificationsRoute
  '/plans': typeof AppPlansRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/referrals': typeof AppReferralsRoute
  '/security': typeof AppSecurityRoute
  '/transactions': typeof AppTransactionsRoute
  '/withdraw': typeof AppWithdrawRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/profile/security': typeof AppProfileSecurityRouteWithChildren
  '/profile/security/fund-password': typeof AppProfileSecurityFundPasswordRoute
  '/profile/security/login-password': typeof AppProfileSecurityLoginPasswordRoute
  '/deposit/crypto/usdt/bep20': typeof AppDepositCryptoUsdtBep20Route
  '/withdraw/crypto/usdt/bep20': typeof AppWithdrawCryptoUsdtBep20Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/support': typeof SupportRoute
  '/admin': typeof AppAdminRoute
  '/admin-earnings': typeof AppAdminEarningsRoute
  '/dashboard': typeof AppDashboardRoute
  '/deposit': typeof AppDepositRoute
  '/notifications': typeof AppNotificationsRoute
  '/plans': typeof AppPlansRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/referrals': typeof AppReferralsRoute
  '/security': typeof AppSecurityRoute
  '/transactions': typeof AppTransactionsRoute
  '/withdraw': typeof AppWithdrawRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/profile/security': typeof AppProfileSecurityRouteWithChildren
  '/profile/security/fund-password': typeof AppProfileSecurityFundPasswordRoute
  '/profile/security/login-password': typeof AppProfileSecurityLoginPasswordRoute
  '/deposit/crypto/usdt/bep20': typeof AppDepositCryptoUsdtBep20Route
  '/withdraw/crypto/usdt/bep20': typeof AppWithdrawCryptoUsdtBep20Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/faq': typeof FaqRoute
  '/support': typeof SupportRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/admin-earnings': typeof AppAdminEarningsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/deposit': typeof AppDepositRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/plans': typeof AppPlansRoute
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/referrals': typeof AppReferralsRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/withdraw': typeof AppWithdrawRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/profile/security': typeof AppProfileSecurityRouteWithChildren
  '/_app/profile/security/fund-password': typeof AppProfileSecurityFundPasswordRoute
  '/_app/profile/security/login-password': typeof AppProfileSecurityLoginPasswordRoute
  '/_app/deposit_/crypto/usdt/bep20': typeof AppDepositCryptoUsdtBep20Route
  '/_app/withdraw_/crypto/usdt/bep20': typeof AppWithdrawCryptoUsdtBep20Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/support'
    | '/admin'
    | '/admin-earnings'
    | '/dashboard'
    | '/deposit'
    | '/notifications'
    | '/plans'
    | '/profile'
    | '/referrals'
    | '/security'
    | '/transactions'
    | '/withdraw'
    | '/login'
    | '/register'
    | '/profile/security'
    | '/profile/security/fund-password'
    | '/profile/security/login-password'
    | '/deposit/crypto/usdt/bep20'
    | '/withdraw/crypto/usdt/bep20'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/support'
    | '/admin'
    | '/admin-earnings'
    | '/dashboard'
    | '/deposit'
    | '/notifications'
    | '/plans'
    | '/profile'
    | '/referrals'
    | '/security'
    | '/transactions'
    | '/withdraw'
    | '/login'
    | '/register'
    | '/profile/security'
    | '/profile/security/fund-password'
    | '/profile/security/login-password'
    | '/deposit/crypto/usdt/bep20'
    | '/withdraw/crypto/usdt/bep20'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/faq'
    | '/support'
    | '/_app/admin'
    | '/_app/admin-earnings'
    | '/_app/dashboard'
    | '/_app/deposit'
    | '/_app/notifications'
    | '/_app/plans'
    | '/_app/profile'
    | '/_app/referrals'
    | '/_app/security'
    | '/_app/transactions'
    | '/_app/withdraw'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/profile/security'
    | '/_app/profile/security/fund-password'
    | '/_app/profile/security/login-password'
    | '/_app/deposit_/crypto/usdt/bep20'
    | '/_app/withdraw_/crypto/usdt/bep20'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  FaqRoute: typeof FaqRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/withdraw': {
      id: '/_app/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/referrals': {
      id: '/_app/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AppReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans': {
      id: '/_app/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deposit': {
      id: '/_app/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof AppDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin-earnings': {
      id: '/_app/admin-earnings'
      path: '/admin-earnings'
      fullPath: '/admin-earnings'
      preLoaderRoute: typeof AppAdminEarningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/security': {
      id: '/_app/profile/security'
      path: '/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof AppProfileSecurityRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/profile/security/login-password': {
      id: '/_app/profile/security/login-password'
      path: '/login-password'
      fullPath: '/profile/security/login-password'
      preLoaderRoute: typeof AppProfileSecurityLoginPasswordRouteImport
      parentRoute: typeof AppProfileSecurityRoute
    }
    '/_app/profile/security/fund-password': {
      id: '/_app/profile/security/fund-password'
      path: '/fund-password'
      fullPath: '/profile/security/fund-password'
      preLoaderRoute: typeof AppProfileSecurityFundPasswordRouteImport
      parentRoute: typeof AppProfileSecurityRoute
    }
    '/_app/withdraw_/crypto/usdt/bep20': {
      id: '/_app/withdraw_/crypto/usdt/bep20'
      path: '/withdraw/crypto/usdt/bep20'
      fullPath: '/withdraw/crypto/usdt/bep20'
      preLoaderRoute: typeof AppWithdrawCryptoUsdtBep20RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deposit_/crypto/usdt/bep20': {
      id: '/_app/deposit_/crypto/usdt/bep20'
      path: '/deposit/crypto/usdt/bep20'
      fullPath: '/deposit/crypto/usdt/bep20'
      preLoaderRoute: typeof AppDepositCryptoUsdtBep20RouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppProfileSecurityRouteChildren {
  AppProfileSecurityFundPasswordRoute: typeof AppProfileSecurityFundPasswordRoute
  AppProfileSecurityLoginPasswordRoute: typeof AppProfileSecurityLoginPasswordRoute
}

const AppProfileSecurityRouteChildren: AppProfileSecurityRouteChildren = {
  AppProfileSecurityFundPasswordRoute: AppProfileSecurityFundPasswordRoute,
  AppProfileSecurityLoginPasswordRoute: AppProfileSecurityLoginPasswordRoute,
}

const AppProfileSecurityRouteWithChildren =
  AppProfileSecurityRoute._addFileChildren(AppProfileSecurityRouteChildren)

interface AppProfileRouteChildren {
  AppProfileSecurityRoute: typeof AppProfileSecurityRouteWithChildren
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileSecurityRoute: AppProfileSecurityRouteWithChildren,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAdminEarningsRoute: typeof AppAdminEarningsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepositRoute: typeof AppDepositRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPlansRoute: typeof AppPlansRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppReferralsRoute: typeof AppReferralsRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
  AppDepositCryptoUsdtBep20Route: typeof AppDepositCryptoUsdtBep20Route
  AppWithdrawCryptoUsdtBep20Route: typeof AppWithdrawCryptoUsdtBep20Route
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAdminEarningsRoute: AppAdminEarningsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepositRoute: AppDepositRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPlansRoute: AppPlansRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppReferralsRoute: AppReferralsRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppWithdrawRoute: AppWithdrawRoute,
  AppDepositCryptoUsdtBep20Route: AppDepositCryptoUsdtBep20Route,
  AppWithdrawCryptoUsdtBep20Route: AppWithdrawCryptoUsdtBep20Route,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  FaqRoute: FaqRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
